name: run tests
on: push

jobs:

    win-x64:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3

        - name: Setup Selenium
          run: pip install selenium

        - name: runs the tests
          run: ./run_all_tests.bat 

