name: run tests
on: push

jobs:

    win-x64:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v1
        - name: runs the tests
          run: |
            sh ./run_all_tests.sh

