name: run tests
on:
  push:
    tags:
      - '*'
jobs:

    linux-x64:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: runs the tests
          run: |
            sh ./run_all_tests.sh

